# Generated by Django 5.2.7 on 2025-12-10 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('address', models.CharField(max_length=20, verbose_name='Адрес')),
                ('company', models.CharField(max_length=100, verbose_name='Компания')),
                ('term', models.CharField(max_length=50, verbose_name='Сроки')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Описание объекта')),
                ('task', models.TextField(verbose_name='Задача')),
                ('solution', models.TextField(verbose_name='Решение')),
                ('gratitude', models.TextField(verbose_name='Благодарность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Изображение')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Галерея проекта',
                'verbose_name_plural': 'Галерея проекта',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
