# Generated by Django 5.2.7 on 2025-12-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectgallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Галерея проекта', 'verbose_name_plural': 'Галерея проекта'},
        ),
    ]
