# Generated by Django 5.2.7 on 2025-11-30 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=20, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='clients/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
