# Generated by Django 5.2.7 on 2025-12-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosection',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео файл'),
        ),
        migrations.AlterField(
            model_name='videosection',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL видео'),
        ),
    ]
