# Generated by Django 5.2.7 on 2025-12-10 12:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptancePerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='acceptance_persons/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Принимающее лицо',
                'verbose_name_plural': 'Принимающее лицо',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('working_hours', models.CharField(max_length=100, verbose_name='Рабочие часы')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='Номер WhatsApp')),
                ('telegram_number', models.CharField(max_length=20, verbose_name='Номер Telegram')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('instagram', models.URLField(verbose_name='Ссылка на Instagram')),
                ('facebook', models.URLField(verbose_name='Ссылка на Facebook')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
