# Generated by Django 5.2.7 on 2025-12-05 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptancePerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='acceptance_persons/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Принимающее лицо',
                'verbose_name_plural': 'Принимающее лицо',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
