# Generated by Django 5.2.7 on 2025-12-10 12:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='company_banners/')),
                ('video', models.FileField(blank=True, null=True, upload_to='company_videos/')),
            ],
            options={
                'verbose_name': 'Баннер компании',
                'verbose_name_plural': 'Баннер компании',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInNumbers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=10, verbose_name='Число')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Компания в цифрах',
                'verbose_name_plural': 'Компания в цифрах',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='company_photo/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фотография компании',
                'verbose_name_plural': 'Фотография компании',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_of_activivty', models.TextField(max_length=255, verbose_name='Сфера деятельности')),
                ('mission', models.TextField(max_length=255, verbose_name='Миссия')),
                ('values', models.TextField(max_length=255, verbose_name='Ценности')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='company_values/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Ценности компании',
                'verbose_name_plural': 'Ценности компании',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, verbose_name='Название документа')),
                ('description', models.TextField(max_length=150, verbose_name='Описание документа')),
                ('file_url', models.FileField(upload_to='company_documents/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ компании',
                'verbose_name_plural': 'Документы компании',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='experts_photos/', verbose_name='Фото')),
                ('experience', models.CharField(max_length=50, verbose_name='Опыт')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Эксперт',
                'verbose_name_plural': 'Эксперты',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
