# Generated by Django 5.2.7 on 2025-12-05 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='company_photo/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фотография компании',
                'verbose_name_plural': 'Фотография компании',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
