# Generated by Django 5.2.7 on 2025-12-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyphoto'),
    ]

    # Documents is already created in 0001_initial; keep this migration as a no-op.
    operations = []
