# Generated by Django 5.2.7 on 2025-12-05 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, verbose_name='Название документа')),
                ('description', models.TextField(max_length=150, verbose_name='Описание документа')),
                ('file_url', models.FileField(upload_to='company_documents/', verbose_name='Документ')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Документ компании',
                'verbose_name_plural': 'Документы компании',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
