# Generated by Django 5.2.7 on 2025-12-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['-created_at'], 'verbose_name': 'Документ компании', 'verbose_name_plural': 'Документы компании'},
        ),
        migrations.RemoveField(
            model_name='documents',
            name='order',
        ),
    ]
