# Generated by Django 5.2.7 on 2025-12-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_documents_options_remove_documents_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybanner',
            old_name='video',
            new_name='video_url',
        ),
        migrations.AddField(
            model_name='companybanner',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео файл'),
        ),
    ]
