# Generated by Django 5.2.7 on 2025-12-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_rename_video_companybanner_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybanner',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='companybanner',
            name='image',
            field=models.ImageField(upload_to='company_banners/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='companybanner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='companybanner',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='company_videos/', verbose_name='Ссылка на видео'),
        ),
    ]
